### PR TITLE
Introduce property-filter-autosuggest derived from internal autosuggest

### PR DESCRIPTION
**Pull request by pan-kot**
### Description

Property filter uses autosuggest internally but requires more features that the public autosuggest API has to offer. The coming changes to the property filter (see https://github.com/cloudscape-design/components/pull/166) would only worsen this problem.

In this PR a new internal property-filter-autosuggest component is introduced that is similar to autosuggest but includes the property filter-related changes. Those extra properties are removed from the internal autosuggest as no longer required.

### How has this been tested?

Existing tests.

### Documentation changes

[*Do the changes include any API documentation changes?*]
- [ ] _Yes, this change contains documentation changes._
- [x] _No._

### Related Links

[*Attach any related links/pull request for this change*]

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- [ ] _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](CONTRIBUTING.md#public-apis)._
- [ ] _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](CONTRIBUTING.md#browsers-support)._
- [ ] _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- [ ] _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- [ ] _Changes are covered with new/existing unit tests?_
- [ ] _Changes are covered with new/existing integration tests?_
</details>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gethinwebster** [comment]
I'm not totally sure about the tradeoff here. It reduces complexity in `autosuggest`, but in turn we get a lot of duplication of a relatively complex component, that we then have to update twice for any future improvements.
To me, it seems like the risk of duplication is larger overall, what is it about the alternative (i.e. the current approach) that you think makes it a worse solution?

**Comment by pan-kot** [comment]
> I'm not totally sure about the tradeoff here. It reduces complexity in `autosuggest`, but in turn we get a lot of duplication of a relatively complex component, that we then have to update twice for any future improvements. To me, it seems like the risk of duplication is larger overall, what is it about the alternative (i.e. the current approach) that you think makes it a worse solution?

I think neither solution is ideal. I'd love to have some abstract autosuggest that takes a string input and offers some value representation be it a list of options or anything and also giving enough flexibility to control what is highlighted etc. If we create such a component, both autosuggest and property-filter can derive from there. However, that would take a decent amount of work (but hopefully we'll get there).

To me, the new property-filter-autosuggest component does not include that much of a duplicated logic - the majority of it is inside the utils that are imported from the autosuggest still. In case we need to update something in there, we'll have a choice to only do it for autosuggest, property-filter-autosuggest, or both components, in which case the logic can be still de-duplicated by introducing it as a util that belongs to the autosuggest scope.

The benefit of having a separate component though, is that we can update it separately and also change the signature. For example, one thing that wasn't done in scope of the current PR is handling of the autosuggest options. Instead of computing the options elsewhere (see [ref](https://github.com/cloudscape-design/components/blob/main/src/property-filter/index.tsx#L70)), this logic can be moved to the new component. The future extension of the property-filter would require at least two new internal properties to the autosuggest that are only needed by the property filter and break the autosuggest's boundaries even more.

Lastly, I think it is easier to transition to the ideal state from having multiple similar components (by reusing the common parts) rather than having the monstrous ones.

**Comment by gethinwebster** [comment]
Ok, this seems reasonable. I think there are two things I'd suggest to minimize the risk:
1. Ensure that we have a ticket somewhere (perhaps BRF? although maybe it's too big for that) to address this technical debt and abstract further.
2. Ensure that people working on a11y are aware of this duplication, as a) a11y-related attributes and functionality seem to be some of the parts that are more duplicated rather than shared and b) this is likely to change in the near future with the a11y audit

**Review by gethinwebster — APPROVED** [review]

**Comment by pan-kot** [comment]
> Ok, this seems reasonable. I think there are two things I'd suggest to minimize the risk:
> 
> 1. Ensure that we have a ticket somewhere (perhaps BRF? although maybe it's too big for that) to address this technical debt and abstract further.
> 2. Ensure that people working on a11y are aware of this duplication, as a) a11y-related attributes and functionality seem to be some of the parts that are more duplicated rather than shared and b) this is likely to change in the near future with the a11y audit

Thanks, I will create a follow-up BRF ticket and share the PR with the a11y people 👍

**Comment by pan-kot** [comment]
Follow-up ticket: 19112

**Pull request merged**
