### PR TITLE
chore: Cleanup ESLint warnings in CI environment

### PR DESCRIPTION
**Pull request by connorlanigan**
### Description

In a typical PR, the linting step produces a large amount of warnings with these two messages:
```
warning  Prop "className" is forbidden on Components  react/forbid-component-props
```
```
warning  Prop "id" is forbidden on Components  react/forbid-component-props
```

Example log: [cloudscape-design/components/.../job/16574616087](https://github.com/cloudscape-design/components/actions/runs/6107496245/job/16574616087?pr=1517#step:7:1)

These warnings currently make up 479 of 503 total warnings (95.2%), and thus reduce the visibility of other (potentially more important) warnings immensely. This has already lead to a "warning fatigue" in the team. Since there are still many use cases for these properties, they cannot just all be removed from the code.

Related links, issue #, if available: n/a

### How has this been tested?

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by just-boris** [comment]
Should we just turn it off, it is not useful? Or scope down to "pages/" directory only, for example?

**Comment by just-boris** [comment]
Every instance of `process.env.CI` is a possible hours spent on debugging why the build passes locally and fails in PR. Should be used very carefully

**Comment by just-boris** [comment]
How about annotating all current usage with eslint-ignore, if we want to keep the rule?

**Comment by connorlanigan** [comment]
That is an option, but, assuming that we want to review them rather than just annotate all of them, it will be a longer process (since there are 479 instances). I think in the meantime these warnings serve no purpose, so I would not want to delay making the warning output useful again until all these instances have been reviewed and updated or annotated.

**Comment by just-boris** [comment]
Still not convinced for CI-only conditions here. You can try discussing it with the other devs. If the majority is fine with that, I will accept

**Comment by connorlanigan** [comment]
Superseded by https://github.com/cloudscape-design/components/pull/1529.

**Pull request closed without merging**
