### PR TITLE
chore: reuse unique ID function to de-duplicate logic

### PR DESCRIPTION
**Pull request by jperals**
### Description

Small follow-up from #715 (see [comment](https://github.com/cloudscape-design/components/pull/715#discussion_r1099963151)): reuse existing `generateUniqueId` logic instead of creating a new one.

Related links, issue #, if available: n/a

### How has this been tested?

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Al-Dani** [comment]
not sure, how much cense is in the following using of the random key on the line 33: 

> content: `This is a flash item with key ${randomKey.split('_').join(' ')}`,

But if it's ok from the context, then there is nothing more from my side

**Review by Al-Dani — APPROVED** [review]

**Comment by jperals** [comment]
@Al-Dani Sorry I saw your message too late. Yes, not sure it makes a lot of sense to do that transformation for rendering, but I don't think it really matters (in the sense that it doesn't break anything) and I preferred to keep the changes minimal. The original logic was not added in #715 but just moved around.

**Comment by just-boris** [comment]
If this value ends up in screenshot tests (where we use props to identify "old" and "new" images, it is going to be a problem).

For safe screenshot tests, we have this helper: https://github.com/cloudscape-design/components/blob/main/pages/utils/pseudo-random.ts

It gives you non-consequent, but deterministic numbers on every run.

--

Also, is there any reason why you cannot use indexes, 1, 2, 3, 4, 5, etc?

**Comment by jperals** [comment]
I am actually considering using this page for screenshot tests right now, so I might do just that (most likely using the simpler index approach). Thanks for the suggestions!

**Pull request merged**
