### PR TITLE
Added hyperlink to AWS in README.md

### LINKED ISSUE #81: [Documentation]: Adding hyperlink to README.md
### Description

Adding a hyperlink to Amazon Web Services (AWS) for quality of life.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate requests

### PR DESCRIPTION
**Pull request by KaevonD**
*Issue #, if available:*
Fixes #81 

*Description of changes:*
Added a hyperlink to AWS in README.md

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by FlorianDr** [comment]
Hey @KaevonD, thank you for your contribution. I have two asks before we can merge this PR:

1. Do you mind using the original PR template including also the last line? 

> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2. Do you have plans to mirror the change to the other `README.md` files? Otherwise, those files become out-of-sync. e.g. https://github.com/cloudscape-design/collection-hooks/blob/main/README.md or https://github.com/cloudscape-design/browser-test-tools/blob/main/README.md

Florian

**Comment by KaevonD** [comment]
Sure thing, sorry about that @FlorianDr . I'll get to adding this change to all the repositories right now.

**Comment by KaevonD** [comment]
@FlorianDr I have added the changes and submitted pull requests for components, collection-hooks, test-utils, theming-core, global-styles, jest-preset, browser-test-tools, and documenter repositories. Please let me know if I missed anything!

**Comment by FlorianDr** [comment]
Great! Thank you for your contribution!

**Review by FlorianDr — APPROVED** [review]

**Pull request merged**
