### PR TITLE
fix: Use recoveryText from i18n provider in Select

### PR DESCRIPTION
**Pull request by Al-Dani**
### Description

We missed couple of properties when implementing i18n 

Related links, issue #, if available: AWSUI-22320

### How has this been tested?

New `i18n` unit tests added

<details>
   <summary>Review checklist</summary>

_The following items are to be evaluated by the author(s) and the reviewer(s)._

#### Correctness

- _Changes include appropriate documentation updates._
- _Changes are backward-compatible if not indicated, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#public-apis)._
- _Changes do not include unsupported browser features, see [`CONTRIBUTING.md`](https://github.com/cloudscape-design/components/blob/main/CONTRIBUTING.md#browsers-support)._
- _Changes were manually tested for accessibility, see [accessibility guidelines](https://cloudscape.design/foundation/core-principles/accessibility/)._

#### Security

- _If the code handles URLs: all URLs are validated through [the `checkSafeUrl` function](https://github.com/cloudscape-design/components/blob/main/src/internal/utils/check-safe-url.ts)._

#### Testing

- _Changes are covered with new/existing unit tests?_
- _Changes are covered with new/existing integration tests?_
</details>

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by abdhalees — APPROVED** [review]

**Comment by just-boris** [comment]
Should there be any tests for it?

**Comment by Al-Dani** [comment]
> Should there be any tests for it?

I thought about it, but not sure how these tests would look like. What we can do is for example remove from `pages` all properties that are coming from i18n and than rely on our a11y and screenshot tests. But this is also kinda manual and therefore pruned to errors

**Comment by just-boris** [comment]
I think, there should be a general test suite for each component that checks that expected built-in strings are rendered.

Please discuss with other team members. It is not good to leave this behavior untested.

**Comment by Al-Dani** [comment]
Created separate `i18n` unit tests for the components in PR. Apparently, we missed more than it was initially reported. So we will gradually add similar tests for other components to make sure we covered all messages.

**Review by abdhalees — APPROVED** [review]

**Pull request merged**
